### PR TITLE
Don't crash if default country not found

### PR DESCRIPTION
**Pull request by AOrobator**

### CODE REVIEW

**Comment by eric-falsquelle** [comment]
Can you please validate this MR ?

**Comment by AOrobator** [comment]
What do you mean by validate? I'm just avoiding the index out of bounds exception.

**Comment by AOrobator** [comment]
Pinging @AlmogBaku

**Comment by AOrobator** [comment]
Hi @AlmogBaku. Please can you make a release that includes this fix? Right now I am forced to copy/paste this library into my project

**Pull request merged**
